apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: kleeat/inventory-webapi
  newName: kleeat/inventory-webapi # {"$imagepolicy":  "wac-hospital:inventory-webapi:name"}
  newTag: main.20260506.2124 # {"$imagepolicy": "wac-hospital:inventory-webapi:tag"}
- name: kleeat/inventory-ufe
  newName: kleeat/inventory-ufe # {"$imagepolicy": "wac-hospital:inventory-ufe:name"}
  newTag: main.20260506.1219 # {"$imagepolicy": "wac-hospital:inventory-ufe:tag"}
