apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: xds-inventory-ufe-content
spec:
  microFrontend: xds-inventory-ufe
  element: xds-inventory-app
  attributes:
    - name: base-path
      value: ./xds-inventory-app/
    - name: api-base
      value: /xds-api
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?xds-inventory-app(/.*)?$"
